name: smart_warehouse_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# =======================================================
# Dependencies: Tất cả các thư viện của bạn nằm ở đây
# =======================================================
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase - ĐÃ CẬP NHẬT PHIÊN BẢN TƯƠNG THÍCH
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.1.0
  firebase_messaging: ^15.0.1
  google_sign_in: ^6.1.4

  # Các thư viện khác

  google_fonts: ^6.2.1 
 
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.1
  path_provider: ^2.0.11
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  http: ^1.5.0
  mobile_scanner: ^6.0.1
 
  

# =======================================================
# Dev Dependencies: Thư viện chỉ dùng để phát triển và test
# =======================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

# =======================================================
# Cấu hình Flutter
# =======================================================
flutter:
  uses-material-design: true
  assets:
    - assets/